name: Test

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      RAILS_ENV: test

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password123
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Setup database
        run: |
          bundle exec rails db:setup

      - name: Run RSpec tests
        run: bundle exec rspec
